# Validate with http://lint.travis-ci.org/
sudo: required
language: node_js
node_js: "6.1"

install:
  - pwd
  - sudo apt-get install lib32stdc++6 lib32z1
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - cd android-sdk-linux/tools
  # list possible installs
  - ./android list sdk --all
  # -u means no ui / -a means all / -t means filter to specifc SDK items
  # echo y to automatically accept android licenses
  - ( while [ 1 ]; do sleep 5; echo y; done ) | ./android update sdk -u -a -t 8,10,33,125,159,166,167
  - cd ../../
env:
  - ANDROID_HOME=~/build/infinitered/ignite/android-sdk-linux
script:
  - ./testRelease.sh master_check latest
