# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    # Choose the version of Node you want here
    - image: cimg/node:18.17.1
  working_directory: /mnt/ramdisk/repo

version: 2.1

parameters:
  "force-release-docs":
    type: boolean
    default: false

orbs:
  publish-docs: infinitered/publish-docs@0.4.9
jobs:
  tests:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install the latest version of bun
          command: curl -fsSL https://bun.sh/install | bash
      - run:
          name: Link bun
          command: sudo ln -s ~/.bun/bin/bun /usr/local/bin/
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ arch }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ arch }}
      - run:
          # We don't want to install CocoaPods on ubuntu where we run the tests.
          name: Set up dummy `pod` command
          command: |
            sudo ln /bin/true /usr/local/bin/pod
      - run:
          name: Ensure git user is configured
          command: |
            git config --global user.email "ci@infinite.red"
            git config --global user.name "Infinite Red"
      - restore_cache:
          name: Restore ignite dependency cache
          key: ignite-deps-cache-{{ .Environment.IGNITE_DEPS_PACKAGER }}-{{ checksum "boilerplate/package.json" }}-{{ arch }}-{{ .Environment.IGNITE_DEPS_KEY_SUFFIX }}
      - run:
          name: Run static tests
          command: yarn format:check && yarn lint && yarn typecheck
      - run:
          name: Run jest tests
          command: yarn test
          no_output_timeout: 5m
      - save_cache:
          name: Save ignite dependency cache
          paths:
            - ~/.cache/ignite
          key: ignite-deps-cache-{{ .Environment.IGNITE_DEPS_PACKAGER }}-{{ checksum "boilerplate/package.json" }}-{{ arch }}-{{ .Environment.IGNITE_DEPS_KEY_SUFFIX }}

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ arch }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build package
          command: yarn build
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to npm
          command: yarn ci:publish # this will be added to your package.json scripts

# Publishing docs details
publish-details: &publish-details
  description: "Infinite Red's hottest boilerplate for React Native."
  git_email: "ci@infinite.red"
  git_username: "Infinite Red CI"
  label: "Ignite"
  project_name: "ignite-cli"
  source_docs_dir: docs
  source_repo_directory: "source"
  target_docs_dir: "docs"
  target_repo: "git@github.com:infinitered/ir-docs.git"
  target_repo_directory: "target"

workflows:
  version: 2
  test_and_release:
    jobs:
      - tests
      - publish:
          context: infinitered-npm-package
          requires:
            - tests
          filters:
            branches:
              only: master
  release-docs:
    when:
      and:
        - not: << pipeline.parameters.force-release-docs >>
        - true # Placeholder for correct YAML structure
    jobs:
      - publish-docs/publish_docs:
          <<: *publish-details
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - '*v[0-9]+\.[0-9]+\.[0-9]+'
  force-release-docs:
    when: << pipeline.parameters.force-release-docs >>
    jobs:
      - publish-docs/publish_docs:
          <<: *publish-details
