# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    # Choose the version of Node you want here
    - image: circleci/node:14.15.1
  working_directory: ~/repo

mac: &mac
  macos:
    xcode: "10.1.0"
  working_directory: ~/repo

version: 2
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          # We don't want to install Cocoapods on ubuntu where we run the tests.
          name: Set up dummy `pod` command
          command: |
            sudo ln /bin/true /usr/local/bin/pod
      - run:
          name: Run tests
          command: yarn ci:test
          no_output_timeout: 15m

  # detox:
  #   <<: *mac
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         name: Restore node modules
  #         keys:
  #           - v1-dependencies-mac-{{ checksum "package.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-mac-
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           yarn install
  #     - save_cache:
  #         name: Save node modules
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-mac-{{ checksum "package.json" }}
  #     - run:
  #         name: Install Detox CLI
  #         command: |
  #           sudo yarn global add detox-cli
  #     - run:
  #         name: Install Ruby and Cocoapods
  #         command: |
  #           sudo apt-get update &&
  #           sudo apt-get install ruby-full &&
  #           sudo gem install cocoapods --no-ri --no-rdoc
  #     - run:
  #         name: Install CocoaPods Specs
  #         command: |
  #           curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
  #     - run:
  #         name: Change Permissions
  #         command: sudo chown -R $(whoami) /Users/distiller/.config/
  #     - run:
  #         name: Install applesimutils
  #         command: brew tap wix/brew && brew install applesimutils
  #     - run:
  #         name: Install fbsimctl
  #         command: brew tap facebook/fb
  #     - run:
  #         name: Create temp directory
  #         command: mkdir tempApp
  #     - run:
  #         name: Ignite app
  #         command: cd tempApp && ignite new DetoxTests --detox --skip-git -b ../
  #     - run:
  #         name: Build Detox in ignited app
  #         command: cd tempApp/DetoxTests && yarn ci:build:e2e
  #     - run:
  #         name: Run detox tests in ignited app
  #         command: cd tempApp/DetoxTests && yarn ci:test:e2e
  #     - run:
  #         name: Remove temp directory
  #         command: rm -rf tempApp

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to NPM
          command: yarn ci:publish # this will be added to your package.json scripts

workflows:
  version: 2
  test_and_release:
    jobs:
      - tests
      # - detox # disabled until we can figure out detox CircleCI problems
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: master
