[package]
name = "igrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
Inflector = "0.11.4"
indicatif = "0.16.2"
