[ignite]
tests = 'ava'
askToOverwrite = false

[ignite.generators]
component = 'ignite-basic-generators'
container = 'ignite-basic-generators'
saga      = 'ignite-basic-generators'
listview  = 'ignite-basic-generators'
screen    = 'ignite-basic-generators'
notfound  = 'ignite-3rd-party'
